services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: sd-backend
    expose:
       - "8080"
    networks:
      - sd-network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: sd-frontend
    ports:
      - "3000:80"
    networks:
      - sd-network

networks:
  sd-network:
      driver: bridge
