services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        HF_TOKEN: ${HF_TOKEN:-no_token_provided}
        HF_MODEL: ${HF_MODEL:-CompVis/stable-diffusion-v1-4}
    image: sd-backend
    expose:
       - "8080"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    networks:
      - sd-network
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: sd-frontend
    ports:
      - "3000:80"
    networks:
      - sd-network

networks:
  sd-network:
      driver: bridge
